# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  imageName: 'star-wars'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: Bash@3
      displayName: Run unit tests
      inputs:
        targetType: 'inline'
        script: 'docker run $(docker image ls -q --filter reference="star-wars") ./gradlew test --tests unit*'
    - task: Bash@3
      displayName: Run integration tests
      inputs:
        targetType: 'inline'
        script: 'docker run $(docker image ls -q --filter reference="star-wars") ./gradlew test --tests integration*'
