version: '3'
services:
  api:
    image: maxalves/starwars-challenge
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=starwars
    volumes:
      - starwars-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - 6380:6380
      - 6379:6379
    volumes:
      - starwars-data:/data

volumes:
  starwars-data: