version: '3'
services:
  mongo-database:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=starwars
    volumes:
      - starwars-data:/data/db

volumes:
  starwars-data: