version: '3'
services:
  mongo-database:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=starwars
    volumes:
      - starwars-data:/data/db

  starwars-redis-db:
    image: redis:latest
    ports:
      - 6380:6380
      - 6379:6379
    volumes:
      - starwars-data:/data

volumes:
  starwars-data: